name: testing

on:
  push:
    branches:
      - main
  pull_request:

permissions:
  contents: read

env:
  GO_VERSION: stable
  TASKFILE_VERSION: 3.x

jobs:
  testing:
    runs-on: ubuntu-latest
    steps:
      - name: Install Task
        uses: arduino/setup-task@b91d5d2c96a56797b48ac1e0e89220bf64044611
        with:
          version: ${{ env.TASKFILE_VERSION }}
          repo-token: ${{ secrets.GITHUB_TOKEN }}
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: ${{ env.GO_VERSION }}
      - name: Run tests
        run: |
          task test

